### ISSUE TITLE
Question: There is any reason to use Swoole as a dependency?

### ISSUE THREAD

**Issue by amandiobm** [jiyis/laravel-nsq#1]
Hi there, I'm very surprised that someone is developing an NSQ drive for the Laravel. It was in my backlog but thankfully you started. Hope in some way help you to improve this package.

I Have a question, why Swoole is a dependency for this package? A lot of shared servers you cannot install pecl dependencies. Which is my case in at least 3 projects that I want to use NSQ.

There is any reason why we have to use Swoole?

Is possible to make as optional?

Best regards, 

Amandio

**Comment by jiyis** [comment]
Hi Amandio，

Thanks for your suggestion. The original intention of developing this package is to let laravel project use `php artisan queue:work nsq` command . As for why use swoole as a dependency,you can refer to the official document [https://www.swoole.co.uk/docs/modules/swoole-client-doc](https://www.swoole.co.uk/docs/modules/swoole-client-doc).

In fact, you can use php strem to connect nsq client. [https://github.com/davegardnerisme/nsqphp](https://github.com/davegardnerisme/nsqphp)
Then use laravel command to consume nsq job.

Sorry for my bad English!  Hope can solve your problem.:smiley:

**Comment by jiyis** [comment]
Hi Amandio，

Thanks for your suggestion. The original intention of developing this package is to let laravel project use `php artisan queue:work nsq` command . As for why use swoole as a dependency.,you can refer to the official document [https://www.swoole.co.uk/docs/modules/swoole-client-doc](url).

In fact, you can use php strem to connect nsq client. [https://github.com/davegardnerisme/nsqphp](url)
Then use laravel command to consume nsq job.

Sorry for my bad English!  Hope can solve your problem.:smiley:
