### ISSUE TITLE
Failed to publish message; required 1 for success, achieved 0. Errors were: 

### ISSUE THREAD

**Issue by wangyabener** [jiyis/laravel-nsq#2]
您好，请问调用push时候抛出这个异常可能是什么原因造成的

**Comment by jiyis** [comment]
把你代码贴一下看看.

**Comment by wangyabener** [comment]
Controller

       // the data you want to be publish
        $str = [
            'id' => 1,
            'userId' => 2,
            'type' => 4,
            'price' => 7,
            'amount' => 8,
            'takerFee' => 10,
            'makerFee' => 11,
            'source' => 12,
        ];

        Queue::connection('nsq')->push(new EntrustTransactionsJob(), $str);

EntrustTransactionsJob

    /**
      * @var int 任务运行的超时时间
      */
     public $timeout = 120;

    /**
     * @var string
     */
     public $topic = 'test';

    /**
     * @var string
     */
     public $channel = 'web';

    /**
     * Create a new job instance.
     *
     * @return void
     */
     public function __construct()
     {
     }

    /**
     * Execute the job.
     *
     * @return void
     */
     public function handle()
     {
        $client = $this->job->getCurrentClient();
        $payload = json_decode($this->job->getMessage(), true);
    }

**Comment by jiyis** [comment]
EntrustTransactionsJob  这个job类的 $topic  属性有设置吗

**Comment by wangyabener** [comment]
有的，刚刚贴错了，已经更新了，麻烦再帮忙看下

**Comment by jiyis** [comment]
看起来像是nsq服务端没有publish成功，Errors were:  这后面没有更详细的错误信息吗？ 还有把你.env 配置的nsqd地址发下，  或者你可以用 curl -d "\<test msg\>" http://127.0.0.1:4151/pub?topic=test    命令看看响应什么

**Comment by wangyabener** [comment]
laravel 报错：

![image](https://user-images.githubusercontent.com/8265351/44561160-c73db880-a785-11e8-8d76-64a2485d99a5.png)


curl结果是ok的：
![image](https://user-images.githubusercontent.com/8265351/44560971-dd974480-a784-11e8-9627-ac2740fd37ad.png)

NsqAdmin：
![image](https://user-images.githubusercontent.com/8265351/44560982-f142ab00-a784-11e8-96d4-85b0f2b4e6b3.png)

.env
![image](https://user-images.githubusercontent.com/8265351/44561017-12a39700-a785-11e8-8474-acf553fdc74f.png)

**Comment by jiyis** [comment]
配错了哦， NSQSD_URL=xxxx:4150    publish是走tcp协议的，所以要配4150端口，4151是http协议的，建议看下文档哦

**Comment by wangyabener** [comment]
好的，已经可以了，Nsq也是第一次接触不太熟悉，十分感谢哈
